name: Install dependencies
description: Install Poetry and the project's dependencies
runs:
  using: "composite"
  steps:
    - name: Install Poetry
      run: pipx install poetry==1.2.2
      shell: bash
    - uses: actions/setup-python@v4
      with:
        cache: poetry
        python-version: "3.9"
    - name: Install dependencies
      run: poetry install --no-interaction
      shell: bash
