name: Test
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-dependencies
      - run: poetry run app format --check
      - run: poetry run app sort-imports --check
      - run: poetry run app lint
      - run: poetry run app typecheck
      - run: poetry run app test
